services:
  - type: web
    name: taskmate-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.render.simple
    dockerContext: .
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"
    healthCheckPath: /api/health
    autoDeploy: true
